name: Complete Check

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '18', '20', '22' ]
    name: Node ${{ matrix.node }} build
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
    - uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: beta
    - uses: browser-actions/setup-firefox@latest
      with:
        firefox-version: latest-beta
    - uses: actions/cache@v4
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-node${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}
    - name: Install
      run: yarn
    - name: Build
      run: yarn build
    - run: sudo apt-get install xvfb
    - name: Test
      run: KARMA_BROWSERS=Chrome,Firefox xvfb-run --auto-servernum yarn test
